[package]
name = "github-dashboard-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-graphql = "4"
async-graphql-warp = "4.0"
base64 = "0.13"
bincode = "1.3"
chrono = "0.4"
git2 = "0.15.0"
graphql_client = "0.11.0"
regex = "1.6"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.82"
sled = "0.34.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.5.9"
tracing = "0.1"
tracing-subscriber = "0.3"
warp = { version = "0.3", features = ["tls"] }

[dev-dependencies]
tempfile = "3"
